type IconSource = 'devicon' | 'simpleicons' | 'local' | 'svgl' | 'selfhst' | 'cloud';

interface IconEntry {
  source: IconSource;
  slug: string;
  variant?: string;
}

export const ICON_REGISTRY: Record<string, IconEntry> = {
  // Dev tools (devicon CDN)
  'Traefik': { source: 'selfhst', slug: 'traefik' },
  'SST': { source: 'svgl', slug: 'sst' },
  'Serverless Framework': { source: 'simpleicons', slug: 'serverless' },
  'OpenFaaS': { source: 'simpleicons', slug: 'openfaas' },
  'Knative': { source: 'simpleicons', slug: 'knative' },
  'Fauna': { source: 'devicon', slug: 'faunadb' },
  'Airbyte': { source: 'simpleicons', slug: 'airbyte' },
  'dbt': { source: 'simpleicons', slug: 'dbt' },
  'Prefect': { source: 'simpleicons', slug: 'prefect' },
  'Dagster': { source: 'selfhst', slug: 'dagster' },
  'Apache Airflow': { source: 'devicon', slug: 'apacheairflow' },
  'WorkOS': { source: 'svgl', slug: 'workos' },
  'Ory': { source: 'devicon', slug: 'ory' },
  'Logto': { source: 'selfhst', slug: 'logto' },
  'SigNoz': { source: 'selfhst', slug: 'signoz' },
  'Logstash': { source: 'devicon', slug: 'logstash' },
  'Fluentd': { source: 'simpleicons', slug: 'fluentd' },
  'Fluent Bit': { source: 'simpleicons', slug: 'fluentbit' },
  'Graylog': { source: 'selfhst', slug: 'graylog' },
  'Splunk': { source: 'selfhst', slug: 'splunk' },
  'New Relic': { source: 'devicon', slug: 'newrelic' },
  'Dynatrace': { source: 'devicon', slug: 'dynatrace' },
  'Istio': { source: 'simpleicons', slug: 'istio' },
  'Linkerd': { source: 'simpleicons', slug: 'linkerd' },
  'EMQX': { source: 'selfhst', slug: 'emqx' },
  'HiveMQ': { source: 'selfhst', slug: 'hivemq' },
  'Eclipse Mosquitto': { source: 'selfhst', slug: 'mosquitto' },
  'Mattermost': { source: 'selfhst', slug: 'mattermost' },
  'Zulip': { source: 'selfhst', slug: 'zulip' },
  'Matrix': { source: 'selfhst', slug: 'matrix' },
  'Microsoft Teams': { source: 'selfhst', slug: 'microsoft-teams' },
  'Apache Avro': { source: 'simpleicons', slug: 'apacheavro' },
  'Apache Parquet': { source: 'simpleicons', slug: 'apacheparquet' },

  'Prettier': { source: 'svgl', slug: 'prettier-icon-dark' },
  'ESLint': { source: 'svgl', slug: 'eslint-icon-dark' },
  'Vitest': { source: 'svgl', slug: 'vitest' },
  'Playwright': { source: 'svgl', slug: 'playwright' },
  'Cypress': { source: 'svgl', slug: 'cypress' },
  'Puppeteer': { source: 'devicon', slug: 'puppeteer' },
  'Webpack': { source: 'devicon', slug: 'webpack' },
  'Rollup': { source: 'devicon', slug: 'rollup' },
  'Babel': { source: 'svgl', slug: 'babel' },
  'PostCSS': { source: 'svgl', slug: 'postcss' },
  'Radix UI': { source: 'svgl', slug: 'radix-ui_dark' },
  'Chakra UI': { source: 'svgl', slug: 'chakra-ui' },
  'Shadcn UI': { source: 'svgl', slug: 'shadcn-ui_dark' },
  'Mantine': { source: 'svgl', slug: 'mantine' },
  'Material UI': { source: 'svgl', slug: 'materialui' },
  'Webflow': { source: 'svgl', slug: 'webflow' },
  'Gatsby': { source: 'selfhst', slug: 'gatsby' },
  'Hugo': { source: 'selfhst', slug: 'hugo' },
  'Jekyll': { source: 'selfhst', slug: 'jekyll' },
  'Eleventy': { source: 'selfhst', slug: 'eleventy' },
  'Nuxt.js': { source: 'selfhst', slug: 'nuxt' },
  'Presto': { source: 'simpleicons', slug: 'presto' },
  'Trino': { source: 'simpleicons', slug: 'trino' },
  'ScyllaDB': { source: 'simpleicons', slug: 'scylladb' },
  'ArangoDB': { source: 'simpleicons', slug: 'arangodb' },
  'MQTT': { source: 'selfhst', slug: 'mqtt' },
  'ZeroMQ': { source: 'simpleicons', slug: 'zeromq' },
  'Crystal': { source: 'devicon', slug: 'crystal' },
  'Nim': { source: 'devicon', slug: 'nim' },
  'Perl': { source: 'devicon', slug: 'perl' },
  'F#': { source: 'devicon', slug: 'fsharp' },
  'Salesforce': { source: 'selfhst', slug: 'salesforce' },
  'HubSpot': { source: 'simpleicons', slug: 'hubspot' },
  'Zendesk': { source: 'simpleicons', slug: 'zendesk' },
  'Intercom': { source: 'simpleicons', slug: 'intercom' },
  'Mixpanel': { source: 'simpleicons', slug: 'mixpanel' },
  'Hotjar': { source: 'simpleicons', slug: 'hotjar' },

  'Weaviate': { source: 'selfhst', slug: 'weaviate' },
  'WebSockets': { source: 'selfhst', slug: 'websocket' },
  'HAProxy': { source: 'selfhst', slug: 'haproxy' },
  'Authelia': { source: 'selfhst', slug: 'authelia' },
  'MinIO': { source: 'selfhst', slug: 'minio' },
  'Plausible': { source: 'selfhst', slug: 'plausible' },
  'Umami': { source: 'selfhst', slug: 'umami' },
  'Uptime Kuma': { source: 'selfhst', slug: 'uptime-kuma' },
  'Nextcloud': { source: 'selfhst', slug: 'nextcloud' },
  'Syncthing': { source: 'selfhst', slug: 'syncthing' },
  'Dex Auth': { source: 'selfhst', slug: 'dex-auth' },
  'AdGuard Home': { source: 'selfhst', slug: 'adguard-home' },
  'Directus': { source: 'selfhst', slug: 'directus' },
  'Ghostty': { source: 'selfhst', slug: 'ghostty' },
  'Gitea': { source: 'selfhst', slug: 'gitea' },
  'Home Assistant': { source: 'selfhst', slug: 'home-assistant' },
  'Jellyfin': { source: 'selfhst', slug: 'jellyfin' },
  'Nginx Proxy Manager': { source: 'selfhst', slug: 'nginx-proxy-manager' },
  'Strapi': { source: 'selfhst', slug: 'strapi' },
  'Vaultwarden': { source: 'selfhst', slug: 'vaultwarden' },
  'WordPress': { source: 'selfhst', slug: 'wordpress' },
  'Appwrite': { source: 'selfhst', slug: 'appwrite' },
  'Baserow': { source: 'selfhst', slug: 'baserow' },
  'Flowise': { source: 'selfhst', slug: 'flowise' },
  'Metabase': { source: 'selfhst', slug: 'metabase' },
  'n8n': { source: 'selfhst', slug: 'n8n' },
  'NocoDB': { source: 'selfhst', slug: 'nocodb' },
  'Open WebUI': { source: 'selfhst', slug: 'open-webui' },
  'PocketBase': { source: 'selfhst', slug: 'pocketbase' },

  'Git': { source: 'svgl', slug: 'git' },
  'Preact': { source: 'svgl', slug: 'preact' },
  'Lit': { source: 'svgl', slug: 'lit' },
  'React Native': { source: 'svgl', slug: 'react_dark' },
  'Flutter': { source: 'svgl', slug: 'flutter' },
  'Electron': { source: 'svgl', slug: 'electron' },
  'Tauri': { source: 'svgl', slug: 'tauri' },
  'Expo': { source: 'svgl', slug: 'expo' },
  'Sass': { source: 'svgl', slug: 'sass' },
  'Bootstrap': { source: 'svgl', slug: 'bootstrap' },
  'Framer Motion': { source: 'svgl', slug: 'framer_dark' },
  'CockroachDB': { source: 'simpleicons', slug: 'cockroachlabs' },
  'Snowflake': { source: 'simpleicons', slug: 'snowflake' },
  'Databricks': { source: 'simpleicons', slug: 'databricks' },
  'Apache Spark': { source: 'devicon', slug: 'apachespark' },
  'OpenSearch': { source: 'simpleicons', slug: 'opensearch' },
  'Memcached': { source: 'devicon', slug: 'memcached' },
  'Netlify': { source: 'svgl', slug: 'netlify' },
  'DigitalOcean': { source: 'svgl', slug: 'digitalocean' },
  'Fastly': { source: 'simpleicons', slug: 'fastly' },
  'Akamai': { source: 'simpleicons', slug: 'akamai' },
  'Linode': { source: 'simpleicons', slug: 'linode' },
  'GitHub': { source: 'svgl', slug: 'github_dark' },
  'Bitbucket': { source: 'devicon', slug: 'bitbucket' },
  'Rancher': { source: 'devicon', slug: 'rancher' },
  'OpenShift': { source: 'simpleicons', slug: 'redhatopenshift' },
  'Portainer': { source: 'devicon', slug: 'portainer' },
  'Caddy': { source: 'simpleicons', slug: 'caddy' },
  'Authentik': { source: 'simpleicons', slug: 'authentik' },
  'Teleport': { source: 'devicon', slug: 'teleport' },
  'Jira': { source: 'devicon', slug: 'jira' },
  'Notion': { source: 'svgl', slug: 'notion' },
  'Linear': { source: 'svgl', slug: 'linear' },
  'Trello': { source: 'svgl', slug: 'trello' },
  'Koa': { source: 'simpleicons', slug: 'koa' },
  'TypeORM': { source: 'svgl', slug: 'typeorm' },
  'Sequelize': { source: 'svgl', slug: 'sequelize' },
  'Mongoose': { source: 'devicon', slug: 'mongoose' },

  'Zig': { source: 'svgl', slug: 'zig' },
  'Elixir': { source: 'devicon', slug: 'elixir' },
  'Clojure': { source: 'devicon', slug: 'clojure' },
  'Haskell': { source: 'svgl', slug: 'haskell' },
  'Scala': { source: 'svgl', slug: 'scala' },
  'Kotlin': { source: 'svgl', slug: 'kotlin' },
  'Swift': { source: 'svgl', slug: 'swift' },
  'PHP': { source: 'svgl', slug: 'php' },
  'Ruby': { source: 'svgl', slug: 'ruby' },
  'C++': { source: 'svgl', slug: 'c-plusplus' },
  'C#': { source: 'svgl', slug: 'csharp' },
  'Java': { source: 'svgl', slug: 'java' },
  'Dart': { source: 'svgl', slug: 'dart' },
  'Lua': { source: 'svgl', slug: 'lua' },
  'Julia': { source: 'svgl', slug: 'julia' },
  'Astro': { source: 'svgl', slug: 'astro-icon-dark' },
  'SolidJS': { source: 'svgl', slug: 'solidjs' },
  'Remix': { source: 'svgl', slug: 'remix_dark' },
  'Qwik': { source: 'svgl', slug: 'qwik' },
  'Angular': { source: 'svgl', slug: 'angular' },
  'Laravel': { source: 'svgl', slug: 'laravel' },
  'Spring Boot': { source: 'svgl', slug: 'spring' },
  'NestJS': { source: 'svgl', slug: 'nestjs' },
  'Ruby on Rails': { source: 'simpleicons', slug: 'rails' },
  'Flask': { source: 'svgl', slug: 'flask-dark' },
  'Gin': { source: 'simpleicons', slug: 'gin' },
  'Fiber': { source: 'devicon', slug: 'fiber' },
  'Phoenix': { source: 'devicon', slug: 'phoenix' },
  'Actix': { source: 'simpleicons', slug: 'actix' },
  'Cassandra': { source: 'devicon', slug: 'cassandra' },
  'ClickHouse': { source: 'devicon', slug: 'clickhouse' },
  'InfluxDB': { source: 'devicon', slug: 'influxdb' },
  'TimescaleDB': { source: 'simpleicons', slug: 'timescale' },
  'Neo4j': { source: 'devicon', slug: 'neo4j' },
  'Typesense': { source: 'svgl', slug: 'typesense' },
  'Milvus': { source: 'simpleicons', slug: 'milvus' },
  'Qdrant': { source: 'svgl', slug: 'qdrant-icon-dark' },
  'Hasura': { source: 'simpleicons', slug: 'hasura' },
  'SurrealDB': { source: 'svgl', slug: 'surrealdb' },
  'RabbitMQ': { source: 'devicon', slug: 'rabbitmq' },
  'Celery': { source: 'simpleicons', slug: 'celery' },
  'NATS': { source: 'devicon', slug: 'nats' },
  'Ansible': { source: 'devicon', slug: 'ansible' },
  'Terraform': { source: 'svgl', slug: 'terraform' },
  'Pulumi': { source: 'svgl', slug: 'pulumi' },
  'ArgoCD': { source: 'devicon', slug: 'argocd' },
  'Jenkins': { source: 'devicon', slug: 'jenkins' },
  'GitHub Actions': { source: 'devicon', slug: 'githubactions' },
  'GitLab CI': { source: 'svgl', slug: 'gitlab' },
  'Nomad': { source: 'devicon', slug: 'nomad' },
  'Consul': { source: 'devicon', slug: 'consul' },
  'Vault': { source: 'devicon', slug: 'vault' },
  'gRPC': { source: 'devicon', slug: 'grpc' },
  'Kong': { source: 'simpleicons', slug: 'kong' },
  'Envoy': { source: 'devicon', slug: 'envoy' },
  'OpenTelemetry': { source: 'devicon', slug: 'opentelemetry' },
  'Jaeger': { source: 'simpleicons', slug: 'jaeger' },
  'Better Auth': { source: 'svgl', slug: 'better-auth_dark' },
  'Keycloak': { source: 'svgl', slug: 'keycloak' },
  'Firebase Auth': { source: 'svgl', slug: 'firebase' },
  'Okta': { source: 'devicon', slug: 'okta' },
  'Bitwarden': { source: 'svgl', slug: 'bitwarden' },
  'LangChain': { source: 'simpleicons', slug: 'langchain' },
  'Hugging Face': { source: 'svgl', slug: 'hugging_face' },
  'PyTorch': { source: 'devicon', slug: 'pytorch' },
  'Ollama': { source: 'svgl', slug: 'ollama_dark' },
  'Cohere': { source: 'svgl', slug: 'cohere' },
  'Replicate': { source: 'svgl', slug: 'replicate_dark' },
  'Slack': { source: 'svgl', slug: 'slack' },
  'Discord': { source: 'svgl', slug: 'discord' },
  'Telegram': { source: 'svgl', slug: 'telegram' },
  'Loops': { source: 'simpleicons', slug: 'loops' },
  'PayPal': { source: 'svgl', slug: 'paypal' },
  'Shopify': { source: 'svgl', slug: 'shopify' },
  'Mailchimp': { source: 'simpleicons', slug: 'mailchimp' },

  'FastAPI': { source: 'svgl', slug: 'fastapi' },
  'MetaMask': { source: 'svgl', slug: 'metamask' },
  'Next.js': { source: 'svgl', slug: 'nextjs_icon_dark' },
  'React': { source: 'svgl', slug: 'react_dark' },
  'Vue': { source: 'svgl', slug: 'vue' },
  'Svelte': { source: 'svgl', slug: 'svelte' },
  'Bun': { source: 'svgl', slug: 'bun' },
  'Node.js': { source: 'svgl', slug: 'nodejs' },
  'Deno': { source: 'svgl', slug: 'deno' },
  'Go': { source: 'devicon', slug: 'go' },
  'Rust': { source: 'svgl', slug: 'rust' },
  'Python': { source: 'svgl', slug: 'python' },
  'TypeScript': { source: 'svgl', slug: 'typescript' },
  'JavaScript': { source: 'svgl', slug: 'javascript' },
  'PostgreSQL': { source: 'svgl', slug: 'postgresql' },
  'MySQL': { source: 'svgl', slug: 'mysql-icon-dark' },
  'MongoDB': { source: 'svgl', slug: 'mongodb-icon-dark' },
  'Redis': { source: 'svgl', slug: 'redis' },
  'SQLite': { source: 'svgl', slug: 'sqlite' },
  'Docker': { source: 'svgl', slug: 'docker' },
  'Kubernetes': { source: 'svgl', slug: 'kubernetes' },
  'Nginx': { source: 'svgl', slug: 'nginx' },
  'GraphQL': { source: 'svgl', slug: 'graphql' },
  'Prisma': { source: 'svgl', slug: 'prisma' },
  'Vite': { source: 'svgl', slug: 'vite' },
  'Tailwind CSS': { source: 'svgl', slug: 'tailwindcss' },
  'Hono': { source: 'svgl', slug: 'hono' },
  'Fastify': { source: 'svgl', slug: 'fastify' },
  'Express': { source: 'devicon', slug: 'express' },
  'Kafka': { source: 'devicon', slug: 'apachekafka' },
  'Elasticsearch': { source: 'devicon', slug: 'elasticsearch' },

  // Simple Icons
  'Elysia': { source: 'svgl', slug: 'elysiajs' },
  'tRPC': { source: 'svgl', slug: 'trpc' },
  'Zod': { source: 'svgl', slug: 'zod' },
  'Drizzle': { source: 'simpleicons', slug: 'drizzle' },
  'Vercel': { source: 'svgl', slug: 'vercel_dark' },
  'Cloudflare': { source: 'svgl', slug: 'cloudflare' },
  'Cloudflare Workers': { source: 'svgl', slug: 'cloudflare-workers' },
  'Cloudflare R2': { source: 'simpleicons', slug: 'cloudflare' },
  'Cloudflare CDN': { source: 'simpleicons', slug: 'cloudflare' },
  'Neon': { source: 'svgl', slug: 'neon' },
  'PlanetScale': { source: 'svgl', slug: 'planetscale' },
  'Supabase': { source: 'svgl', slug: 'supabase' },
  'Supabase PostgreSQL': { source: 'svgl', slug: 'supabase' },
  'Turso': { source: 'svgl', slug: 'turso-dark' },
  'Upstash': { source: 'svgl', slug: 'upstash' },
  'Stripe': { source: 'svgl', slug: 'stripe' },
  'Resend': { source: 'svgl', slug: 'resend-icon-black' },
  'Mailgun': { source: 'simpleicons', slug: 'mailgun' },
  'SendGrid': { source: 'simpleicons', slug: 'twilio' },
  'Twilio': { source: 'svgl', slug: 'twilio' },
  'GitHub OAuth': { source: 'simpleicons', slug: 'github' },
  'Google OAuth': { source: 'svgl', slug: 'google' },
  'Clerk': { source: 'svgl', slug: 'clerk-icon-dark' },
  'Auth0': { source: 'svgl', slug: 'auth0' },
  'PostHog': { source: 'svgl', slug: 'posthog' },
  'Sentry': { source: 'svgl', slug: 'sentry' },
  'Datadog': { source: 'svgl', slug: 'datadog' },
  'Grafana': { source: 'svgl', slug: 'grafana' },
  'Prometheus': { source: 'simpleicons', slug: 'prometheus' },
  'Railway': { source: 'svgl', slug: 'railway' },
  'Fly.io': { source: 'simpleicons', slug: 'flydotio' },
  'Render': { source: 'simpleicons', slug: 'render' },
  'Heroku': { source: 'svgl', slug: 'heroku' },
  'Algolia': { source: 'svgl', slug: 'algolia' },
  'OpenAI': { source: 'svgl', slug: 'openai_dark' },
  'Anthropic': { source: 'svgl', slug: 'anthropic_black' },
  'Meilisearch': { source: 'simpleicons', slug: 'meilisearch' },
  'Django': { source: 'svgl', slug: 'django' },
  'postgres': { source: 'svgl', slug: 'postgresql' },
  'AI Service (Python)': { source: 'devicon', slug: 'python' },
  'AWS S3': { source: 'cloud', slug: 'aws/service/Storage/64/Amazon-Simple-Storage-Service.svg' },
  'Amazon S3': { source: 'cloud', slug: 'aws/service/Storage/64/Amazon-Simple-Storage-Service.svg' },
  'S3': { source: 'cloud', slug: 'aws/service/Storage/64/Amazon-Simple-Storage-Service.svg' },

  // AWS Services
  'AWS Lambda': { source: 'cloud', slug: 'aws/service/Compute/64/AWS-Lambda.svg' },
  'Lambda': { source: 'cloud', slug: 'aws/service/Compute/64/AWS-Lambda.svg' },
  'Amazon RDS': { source: 'cloud', slug: 'aws/service/Database/64/Amazon-RDS.svg' },
  'AWS RDS': { source: 'cloud', slug: 'aws/service/Database/64/Amazon-RDS.svg' },
  'RDS': { source: 'cloud', slug: 'aws/service/Database/64/Amazon-RDS.svg' },
  'Amazon DynamoDB': { source: 'cloud', slug: 'aws/service/Database/64/Amazon-DynamoDB.svg' },
  'AWS DynamoDB': { source: 'cloud', slug: 'aws/service/Database/64/Amazon-DynamoDB.svg' },
  'DynamoDB': { source: 'cloud', slug: 'aws/service/Database/64/Amazon-DynamoDB.svg' },
  'Amazon SQS': { source: 'cloud', slug: 'aws/service/App-Integration/64/Amazon-Simple-Queue-Service.svg' },
  'AWS SQS': { source: 'cloud', slug: 'aws/service/App-Integration/64/Amazon-Simple-Queue-Service.svg' },
  'SQS': { source: 'cloud', slug: 'aws/service/App-Integration/64/Amazon-Simple-Queue-Service.svg' },
  'Amazon SES': { source: 'cloud', slug: 'aws/service/Business-Applications/64/Amazon-Simple-Email-Service.svg' },
  'AWS SES': { source: 'cloud', slug: 'aws/service/Business-Applications/64/Amazon-Simple-Email-Service.svg' },
  'SES': { source: 'cloud', slug: 'aws/service/Business-Applications/64/Amazon-Simple-Email-Service.svg' },
  'Amazon EC2': { source: 'cloud', slug: 'aws/service/Compute/64/Amazon-EC2.svg' },
  'AWS EC2': { source: 'cloud', slug: 'aws/service/Compute/64/Amazon-EC2.svg' },
  'EC2': { source: 'cloud', slug: 'aws/service/Compute/64/Amazon-EC2.svg' },
  'Amazon ECS': { source: 'cloud', slug: 'aws/service/Containers/64/Amazon-Elastic-Container-Service.svg' },
  'AWS ECS': { source: 'cloud', slug: 'aws/service/Containers/64/Amazon-Elastic-Container-Service.svg' },
  'ECS': { source: 'cloud', slug: 'aws/service/Containers/64/Amazon-Elastic-Container-Service.svg' },
  'Amazon EKS': { source: 'cloud', slug: 'aws/service/Containers/64/Amazon-Elastic-Kubernetes-Service.svg' },
  'AWS EKS': { source: 'cloud', slug: 'aws/service/Containers/64/Amazon-Elastic-Kubernetes-Service.svg' },
  'EKS': { source: 'cloud', slug: 'aws/service/Containers/64/Amazon-Elastic-Kubernetes-Service.svg' },
  'Amazon CloudFront': { source: 'cloud', slug: 'aws/service/Networking-Content-Delivery/64/Amazon-CloudFront.svg' },
  'AWS CloudFront': { source: 'cloud', slug: 'aws/service/Networking-Content-Delivery/64/Amazon-CloudFront.svg' },
  'CloudFront': { source: 'cloud', slug: 'aws/service/Networking-Content-Delivery/64/Amazon-CloudFront.svg' },
  'Amazon API Gateway': { source: 'cloud', slug: 'aws/service/App-Integration/64/Amazon-API-Gateway.svg' },
  'AWS API Gateway': { source: 'cloud', slug: 'aws/service/App-Integration/64/Amazon-API-Gateway.svg' },
  'API Gateway': { source: 'cloud', slug: 'aws/service/App-Integration/64/Amazon-API-Gateway.svg' },
  'Amazon Cognito': { source: 'cloud', slug: 'aws/service/Security-Identity-Compliance/64/Amazon-Cognito.svg' },
  'AWS Cognito': { source: 'cloud', slug: 'aws/service/Security-Identity-Compliance/64/Amazon-Cognito.svg' },
  'Cognito': { source: 'cloud', slug: 'aws/service/Security-Identity-Compliance/64/Amazon-Cognito.svg' },
  'Amazon Route 53': { source: 'cloud', slug: 'aws/service/Networking-Content-Delivery/64/Amazon-Route-53.svg' },
  'AWS Route 53': { source: 'cloud', slug: 'aws/service/Networking-Content-Delivery/64/Amazon-Route-53.svg' },
  'Route 53': { source: 'cloud', slug: 'aws/service/Networking-Content-Delivery/64/Amazon-Route-53.svg' },
  'Amazon ElastiCache': { source: 'cloud', slug: 'aws/service/Database/64/Amazon-ElastiCache.svg' },
  'AWS ElastiCache': { source: 'cloud', slug: 'aws/service/Database/64/Amazon-ElastiCache.svg' },
  'ElastiCache': { source: 'cloud', slug: 'aws/service/Database/64/Amazon-ElastiCache.svg' },
  'Amazon EventBridge': { source: 'cloud', slug: 'aws/service/App-Integration/64/Amazon-EventBridge.svg' },
  'AWS EventBridge': { source: 'cloud', slug: 'aws/service/App-Integration/64/Amazon-EventBridge.svg' },
  'EventBridge': { source: 'cloud', slug: 'aws/service/App-Integration/64/Amazon-EventBridge.svg' },
  'Amazon SNS': { source: 'cloud', slug: 'aws/service/App-Integration/64/Amazon-Simple-Notification-Service.svg' },
  'AWS SNS': { source: 'cloud', slug: 'aws/service/App-Integration/64/Amazon-Simple-Notification-Service.svg' },
  'SNS': { source: 'cloud', slug: 'aws/service/App-Integration/64/Amazon-Simple-Notification-Service.svg' },
  'Amazon Kinesis': { source: 'cloud', slug: 'aws/service/Analytics/64/Amazon-Kinesis.svg' },
  'AWS Kinesis': { source: 'cloud', slug: 'aws/service/Analytics/64/Amazon-Kinesis.svg' },
  'Kinesis': { source: 'cloud', slug: 'aws/service/Analytics/64/Amazon-Kinesis.svg' },
  'AWS Step Functions': { source: 'cloud', slug: 'aws/service/App-Integration/64/AWS-Step-Functions.svg' },
  'Step Functions': { source: 'cloud', slug: 'aws/service/App-Integration/64/AWS-Step-Functions.svg' },
  'AWS Fargate': { source: 'cloud', slug: 'aws/service/Containers/64/AWS-Fargate.svg' },
  'Fargate': { source: 'cloud', slug: 'aws/service/Containers/64/AWS-Fargate.svg' },
  'Amazon Aurora': { source: 'cloud', slug: 'aws/service/Database/64/Amazon-Aurora.svg' },
  'AWS Aurora': { source: 'cloud', slug: 'aws/service/Database/64/Amazon-Aurora.svg' },
  'Aurora': { source: 'cloud', slug: 'aws/service/Database/64/Amazon-Aurora.svg' },
  'AWS Secrets Manager': { source: 'cloud', slug: 'aws/service/Security-Identity-Compliance/64/AWS-Secrets-Manager.svg' },
  'Secrets Manager': { source: 'cloud', slug: 'aws/service/Security-Identity-Compliance/64/AWS-Secrets-Manager.svg' },
  'AWS WAF': { source: 'cloud', slug: 'aws/service/Security-Identity-Compliance/64/AWS-WAF.svg' },
  'WAF': { source: 'cloud', slug: 'aws/service/Security-Identity-Compliance/64/AWS-WAF.svg' },
  'Amazon VPC': { source: 'cloud', slug: 'aws/service/Networking-Content-Delivery/64/Amazon-Virtual-Private-Cloud.svg' },
  'AWS VPC': { source: 'cloud', slug: 'aws/service/Networking-Content-Delivery/64/Amazon-Virtual-Private-Cloud.svg' },
  'VPC': { source: 'cloud', slug: 'aws/service/Networking-Content-Delivery/64/Amazon-Virtual-Private-Cloud.svg' },
  'AWS IAM': { source: 'cloud', slug: 'aws/service/Security-Identity-Compliance/64/AWS-Identity-and-Access-Management.svg' },
  'IAM': { source: 'cloud', slug: 'aws/service/Security-Identity-Compliance/64/AWS-Identity-and-Access-Management.svg' },
  'Amazon CloudWatch': { source: 'cloud', slug: 'aws/service/Management-Governance/64/Amazon-CloudWatch.svg' },
  'AWS CloudWatch': { source: 'cloud', slug: 'aws/service/Management-Governance/64/Amazon-CloudWatch.svg' },
  'CloudWatch': { source: 'cloud', slug: 'aws/service/Management-Governance/64/Amazon-CloudWatch.svg' },
  'Amazon Athena': { source: 'cloud', slug: 'aws/service/Analytics/64/Amazon-Athena.svg' },
  'AWS Athena': { source: 'cloud', slug: 'aws/service/Analytics/64/Amazon-Athena.svg' },
  'Athena': { source: 'cloud', slug: 'aws/service/Analytics/64/Amazon-Athena.svg' },
  'Amazon Redshift': { source: 'cloud', slug: 'aws/service/Analytics/64/Amazon-Redshift.svg' },
  'AWS Redshift': { source: 'cloud', slug: 'aws/service/Analytics/64/Amazon-Redshift.svg' },
  'Redshift': { source: 'cloud', slug: 'aws/service/Analytics/64/Amazon-Redshift.svg' },
  'Amazon Bedrock': { source: 'simpleicons', slug: 'amazonwebservices' },
  'AWS Bedrock': { source: 'simpleicons', slug: 'amazonwebservices' },
  'Bedrock': { source: 'simpleicons', slug: 'amazonwebservices' },
  'AWS ALB': { source: 'cloud', slug: 'aws/service/Networking-Content-Delivery/64/Elastic-Load-Balancing.svg' },
  'ALB': { source: 'cloud', slug: 'aws/service/Networking-Content-Delivery/64/Elastic-Load-Balancing.svg' },
  'ELB': { source: 'cloud', slug: 'aws/service/Networking-Content-Delivery/64/Elastic-Load-Balancing.svg' },
  'AWS KMS': { source: 'cloud', slug: 'aws/service/Security-Identity-Compliance/64/AWS-Key-Management-Service.svg' },
  'KMS': { source: 'cloud', slug: 'aws/service/Security-Identity-Compliance/64/AWS-Key-Management-Service.svg' },
  'jose': { source: 'simpleicons', slug: 'jwt' },
  'jwt': { source: 'simpleicons', slug: 'jwt' },
  'jsonwebtoken': { source: 'simpleicons', slug: 'jwt' },

  // GCP Services
  'GCP Cloud Run': { source: 'cloud', slug: 'gcp/cloud_run/cloud_run.svg' },
  'GCP Cloud Functions': { source: 'cloud', slug: 'gcp/cloud_functions/cloud_functions.svg' },
  'GCP BigQuery': { source: 'cloud', slug: 'gcp/bigquery/bigquery.svg' },
  'GCP Pub/Sub': { source: 'cloud', slug: 'gcp/pubsub/pubsub.svg' },
  'GCP Cloud Storage': { source: 'cloud', slug: 'gcp/cloud_storage/cloud_storage.svg' },
  'GCP Firebase': { source: 'simpleicons', slug: 'firebase' },
  'GCP Firestore': { source: 'cloud', slug: 'gcp/firestore/firestore.svg' },
  'GCP Cloud SQL': { source: 'cloud', slug: 'gcp/cloud_sql/cloud_sql.svg' },
  'GCP Vertex AI': { source: 'cloud', slug: 'gcp/vertexai/vertexai.svg' },
  'GCP GKE': { source: 'cloud', slug: 'gcp/google_kubernetes_engine/google_kubernetes_engine.svg' },
  'GCP Cloud Armor': { source: 'cloud', slug: 'gcp/cloud_armor/cloud_armor.svg' },
  'GCP Load Balancer': { source: 'cloud', slug: 'gcp/cloud_load_balancing/cloud_load_balancing.svg' },
  'GCP Memorystore': { source: 'cloud', slug: 'gcp/memorystore/memorystore.svg' },
  'GCP Spanner': { source: 'cloud', slug: 'gcp/cloud_spanner/cloud_spanner.svg' },
  'GCP Secret Manager': { source: 'cloud', slug: 'gcp/secret_manager/secret_manager.svg' },
  'GCS': { source: 'cloud', slug: 'gcp/cloud_storage/cloud_storage.svg' },
  'GKE': { source: 'cloud', slug: 'gcp/google_kubernetes_engine/google_kubernetes_engine.svg' },
  'BQ': { source: 'cloud', slug: 'gcp/bigquery/bigquery.svg' },

  // Additional Essential Tools & Friendly Aliases
  'ElysiaJS': { source: 'svgl', slug: 'elysiajs' },
  'Google Analytics': { source: 'svgl', slug: 'google-analytics' },
  'TanStack': { source: 'svgl', slug: 'tanstack' },
  'TanStack Query': { source: 'svgl', slug: 'reactquery' },
  'React Query': { source: 'svgl', slug: 'reactquery' },
  'React Hook Form': { source: 'svgl', slug: 'react-hook-form' },
  'pgsql': { source: 'svgl', slug: 'postgresql' },
  'pg': { source: 'svgl', slug: 'postgresql' },
  'postgresql': { source: 'svgl', slug: 'postgresql' },
};

const DEVICON_BASE = 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons';

function buildIconUrl(entry: IconEntry): string {
  switch (entry.source) {
    case 'devicon':
      const variant = entry.variant ?? 'original';
      return `${DEVICON_BASE}/${entry.slug}/${entry.slug}-${variant}.svg`;
    case 'simpleicons':
      return `https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/${entry.slug}.svg`;
    case 'svgl':
      return `https://svgl.app/library/${entry.slug}.svg`;
    case 'selfhst':
      return `https://cdn.jsdelivr.net/gh/selfhst/icons/svg/${entry.slug}.svg`;
    case 'cloud':
      return `https://cdn.jsdelivr.net/gh/tf2d2/icons@main/${entry.slug}`;
    case 'local':
      return entry.slug; // static public path
  }
}

function normalize(label: string): string {
  return label.toLowerCase().replace(/[^a-z0-9]/g, '');
}

// Full path registries of cloud assets
const AWS_PATHS = [
  'aws/service/Analytics/64/AWS-Clean-Rooms.svg',
  'aws/service/Analytics/64/AWS-Data-Exchange.svg',
  'aws/service/Analytics/64/AWS-Data-Pipeline.svg',
  'aws/service/Analytics/64/AWS-Glue-DataBrew.svg',
  'aws/service/Analytics/64/AWS-Glue-Elastic-Views.svg',
  'aws/service/Analytics/64/AWS-Glue.svg',
  'aws/service/Analytics/64/AWS-Lake-Formation.svg',
  'aws/service/Analytics/64/Amazon-Athena.svg',
  'aws/service/Analytics/64/Amazon-CloudSearch.svg',
  'aws/service/Analytics/64/Amazon-DataZone.svg',
  'aws/service/Analytics/64/Amazon-EMR.svg',
  'aws/service/Analytics/64/Amazon-FinSpace.svg',
  'aws/service/Analytics/64/Amazon-Kinesis-Data-Analytics.svg',
  'aws/service/Analytics/64/Amazon-Kinesis-Data-Firehose.svg',
  'aws/service/Analytics/64/Amazon-Kinesis-Data-Streams.svg',
  'aws/service/Analytics/64/Amazon-Kinesis-Video-Streams.svg',
  'aws/service/Analytics/64/Amazon-Kinesis.svg',
  'aws/service/Analytics/64/Amazon-Managed-Streaming-for-Apache-Kafka.svg',
  'aws/service/Analytics/64/Amazon-OpenSearch-Service.svg',
  'aws/service/Analytics/64/Amazon-QuickSight.svg',
  'aws/service/Analytics/64/Amazon-Redshift.svg',
  'aws/service/App-Integration/64/AWS-AppSync.svg',
  'aws/service/App-Integration/64/AWS-Console-Mobile-Application.svg',
  'aws/service/App-Integration/64/AWS-Express-Workflows.svg',
  'aws/service/App-Integration/64/AWS-Step-Functions.svg',
  'aws/service/App-Integration/64/Amazon-API-Gateway.svg',
  'aws/service/App-Integration/64/Amazon-AppFlow.svg',
  'aws/service/App-Integration/64/Amazon-EventBridge.svg',
  'aws/service/App-Integration/64/Amazon-MQ.svg',
  'aws/service/App-Integration/64/Amazon-Managed-Workflows-for-Apache-Airflow.svg',
  'aws/service/App-Integration/64/Amazon-Simple-Notification-Service.svg',
  'aws/service/App-Integration/64/Amazon-Simple-Queue-Service.svg',
  'aws/service/Blockchain/64/Amazon-Managed-Blockchain.svg',
  'aws/service/Blockchain/64/Amazon-Quantum-Ledger-Database.svg',
  'aws/service/Business-Applications/64/AWS-Supply-Chain.svg',
  'aws/service/Business-Applications/64/AWS-Wickr.svg',
  'aws/service/Business-Applications/64/Alexa-For-Business.svg',
  'aws/service/Business-Applications/64/Amazon-Chime-SDK.svg',
  'aws/service/Business-Applications/64/Amazon-Chime.svg',
  'aws/service/Business-Applications/64/Amazon-Connect.svg',
  'aws/service/Business-Applications/64/Amazon-Honeycode.svg',
  'aws/service/Business-Applications/64/Amazon-Pinpoint-APIs.svg',
  'aws/service/Business-Applications/64/Amazon-Pinpoint.svg',
  'aws/service/Business-Applications/64/Amazon-Simple-Email-Service.svg',
  'aws/service/Business-Applications/64/Amazon-WorkDocs-SDK.svg',
  'aws/service/Business-Applications/64/Amazon-WorkDocs.svg',
  'aws/service/Business-Applications/64/Amazon-WorkMail.svg',
  'aws/service/Cloud-Financial-Management/64/AWS-Application-Cost-Profiler.svg',
  'aws/service/Cloud-Financial-Management/64/AWS-Billing-Conductor.svg',
  'aws/service/Cloud-Financial-Management/64/AWS-Budgets.svg',
  'aws/service/Cloud-Financial-Management/64/AWS-Cost-Explorer.svg',
  'aws/service/Cloud-Financial-Management/64/AWS-Cost-and-Usage-Report.svg',
  'aws/service/Cloud-Financial-Management/64/Reserved-Instance-Reporting.svg',
  'aws/service/Cloud-Financial-Management/64/Savings-Plans.svg',
  'aws/service/Compute/64/AWS-App-Runner.svg',
  'aws/service/Compute/64/AWS-Batch.svg',
  'aws/service/Compute/64/AWS-Compute-Optimizer.svg',
  'aws/service/Compute/64/AWS-Elastic-Beanstalk.svg',
  'aws/service/Compute/64/AWS-Lambda.svg',
  'aws/service/Compute/64/AWS-Local-Zones.svg',
  'aws/service/Compute/64/AWS-Nitro-Enclaves.svg',
  'aws/service/Compute/64/AWS-Outposts-family.svg',
  'aws/service/Compute/64/AWS-Outposts-rack.svg',
  'aws/service/Compute/64/AWS-Outposts-servers.svg',
  'aws/service/Compute/64/AWS-Parallel-Cluster.svg',
  'aws/service/Compute/64/AWS-Serverless-Application-Repository.svg',
  'aws/service/Compute/64/AWS-SimSpace-Weaver.svg',
  'aws/service/Compute/64/AWS-Thinkbox-Deadline.svg',
  'aws/service/Compute/64/AWS-Thinkbox-Frost.svg',
  'aws/service/Compute/64/AWS-Thinkbox-Krakatoa.svg',
  'aws/service/Compute/64/AWS-Thinkbox-Sequoia.svg',
  'aws/service/Compute/64/AWS-Thinkbox-Stoke.svg',
  'aws/service/Compute/64/AWS-Thinkbox-XMesh.svg',
  'aws/service/Compute/64/AWS-Wavelength.svg',
  'aws/service/Compute/64/Amazon-EC2-Auto-Scaling.svg',
  'aws/service/Compute/64/Amazon-EC2-Image-Builder.svg',
  'aws/service/Compute/64/Amazon-EC2.svg',
  'aws/service/Compute/64/Amazon-Genomics-CLI.svg',
  'aws/service/Compute/64/Amazon-Lightsail-for-Research.svg',
  'aws/service/Compute/64/Amazon-Lightsail.svg',
  'aws/service/Compute/64/Bottlerocket.svg',
  'aws/service/Compute/64/Elastic-Fabric-Adapter.svg',
  'aws/service/Compute/64/NICE-DCV.svg',
  'aws/service/Compute/64/NICE-EnginFrame.svg',
  'aws/service/Compute/64/VMware-Cloud-on-AWS.svg',
  'aws/service/Containers/64/AWS-Fargate.svg',
  'aws/service/Containers/64/Amazon-ECS-Anywhere.svg',
  'aws/service/Containers/64/Amazon-EKS-Anywhere.svg',
  'aws/service/Containers/64/Amazon-EKS-Cloud.svg',
  'aws/service/Containers/64/Amazon-EKS-Distro.svg',
  'aws/service/Containers/64/Amazon-Elastic-Container-Registry.svg',
  'aws/service/Containers/64/Amazon-Elastic-Container-Service.svg',
  'aws/service/Containers/64/Amazon-Elastic-Kubernetes-Service.svg',
  'aws/service/Containers/64/Red-Hat-OpenShift-Service-on-AWS.svg',
  'aws/service/Customer-Enablement/64/AWS-Activate.svg',
  'aws/service/Customer-Enablement/64/AWS-IQ.svg',
  'aws/service/Customer-Enablement/64/AWS-Managed-Services.svg',
  'aws/service/Customer-Enablement/64/AWS-Professional-Services.svg',
  'aws/service/Customer-Enablement/64/AWS-Support.svg',
  'aws/service/Customer-Enablement/64/AWS-Training-Certification.svg',
  'aws/service/Customer-Enablement/64/AWS-re-Post.svg',
  'aws/service/Database/64/AWS-Database-Migration-Service.svg',
  'aws/service/Database/64/Amazon-Aurora.svg',
  'aws/service/Database/64/Amazon-DocumentDB.svg',
  'aws/service/Database/64/Amazon-DynamoDB.svg',
  'aws/service/Database/64/Amazon-ElastiCache.svg',
  'aws/service/Database/64/Amazon-Keyspaces.svg',
  'aws/service/Database/64/Amazon-MemoryDB-for-Redis.svg',
  'aws/service/Database/64/Amazon-Neptune.svg',
  'aws/service/Database/64/Amazon-RDS-on-VMware.svg',
  'aws/service/Database/64/Amazon-RDS.svg',
  'aws/service/Database/64/Amazon-Timestream.svg',
  'aws/service/Developer-Tools/64/AWS-Application-Composer.svg',
  'aws/service/Developer-Tools/64/AWS-Cloud-Control-API.svg',
  'aws/service/Developer-Tools/64/AWS-Cloud-Development-Kit.svg',
  'aws/service/Developer-Tools/64/AWS-Cloud9.svg',
  'aws/service/Developer-Tools/64/AWS-CloudShell.svg',
  'aws/service/Developer-Tools/64/AWS-CodeArtifact.svg',
  'aws/service/Developer-Tools/64/AWS-CodeBuild.svg',
  'aws/service/Developer-Tools/64/AWS-CodeCommit.svg',
  'aws/service/Developer-Tools/64/AWS-CodeDeploy.svg',
  'aws/service/Developer-Tools/64/AWS-CodePipeline.svg',
  'aws/service/Developer-Tools/64/AWS-CodeStar.svg',
  'aws/service/Developer-Tools/64/AWS-Command-Line-Interface.svg',
  'aws/service/Developer-Tools/64/AWS-Tools-and-SDKs.svg',
  'aws/service/Developer-Tools/64/AWS-X-Ray.svg',
  'aws/service/Developer-Tools/64/Amazon-CodeCatalyst.svg',
  'aws/service/Developer-Tools/64/Amazon-Corretto.svg',
  'aws/service/End-User-Computing/64/Amazon-AppStream.svg',
  'aws/service/End-User-Computing/64/Amazon-WorkLink.svg',
  'aws/service/End-User-Computing/64/Amazon-WorkSpaces-Family.svg',
  'aws/service/Front-End-Web-Mobile/64/AWS-Amplify.svg',
  'aws/service/Front-End-Web-Mobile/64/AWS-Device-Farm.svg',
  'aws/service/Front-End-Web-Mobile/64/Amazon-Location-Service.svg',
  'aws/service/Games/64/AWS-GameKit.svg',
  'aws/service/Games/64/Amazon-GameLift.svg',
  'aws/service/Games/64/Amazon-GameSparks.svg',
  'aws/service/Games/64/Open-3D-Engine.svg',
  'aws/service/General-Icons/64/AWS-Marketplace_Dark.svg',
  'aws/service/General-Icons/64/AWS-Marketplace_Light.svg',
  'aws/service/Internet-of-Things/64/AWS-IoT-1-Click.svg',
  'aws/service/Internet-of-Things/64/AWS-IoT-Analytics.svg',
  'aws/service/Internet-of-Things/64/AWS-IoT-Button.svg',
  'aws/service/Internet-of-Things/64/AWS-IoT-Core.svg',
  'aws/service/Internet-of-Things/64/AWS-IoT-Device-Defender.svg',
  'aws/service/Internet-of-Things/64/AWS-IoT-Device-Management.svg',
  'aws/service/Internet-of-Things/64/AWS-IoT-EduKit.svg',
  'aws/service/Internet-of-Things/64/AWS-IoT-Events.svg',
  'aws/service/Internet-of-Things/64/AWS-IoT-ExpressLink.svg',
  'aws/service/Internet-of-Things/64/AWS-IoT-FleetWise.svg',
  'aws/service/Internet-of-Things/64/AWS-IoT-Greengrass.svg',
  'aws/service/Internet-of-Things/64/AWS-IoT-RoboRunner.svg',
  'aws/service/Internet-of-Things/64/AWS-IoT-SiteWise.svg',
  'aws/service/Internet-of-Things/64/AWS-IoT-Things-Graph.svg',
  'aws/service/Internet-of-Things/64/AWS-IoT-TwinMaker.svg',
  'aws/service/Internet-of-Things/64/FreeRTOS.svg',
  'aws/service/Machine-Learning/64/AWS-Deep-Learning-AMIs.svg',
  'aws/service/Machine-Learning/64/AWS-Deep-Learning-Containers.svg',
  'aws/service/Machine-Learning/64/AWS-DeepComposer.svg',
  'aws/service/Machine-Learning/64/AWS-DeepLens.svg',
  'aws/service/Machine-Learning/64/AWS-DeepRacer.svg',
  'aws/service/Machine-Learning/64/AWS-Neuron.svg',
  'aws/service/Machine-Learning/64/AWS-Panorama.svg',
  'aws/service/Machine-Learning/64/Amazon-Augmented-AI-A2I.svg',
  'aws/service/Machine-Learning/64/Amazon-CodeGuru.svg',
  'aws/service/Machine-Learning/64/Amazon-CodeWhisperer.svg',
  'aws/service/Machine-Learning/64/Amazon-Comprehend-Medical.svg',
  'aws/service/Machine-Learning/64/Amazon-Comprehend.svg',
  'aws/service/Machine-Learning/64/Amazon-DevOps-Guru.svg',
  'aws/service/Machine-Learning/64/Amazon-Elastic-Inference.svg',
  'aws/service/Machine-Learning/64/Amazon-Forecast.svg',
  'aws/service/Machine-Learning/64/Amazon-Fraud-Detector.svg',
  'aws/service/Machine-Learning/64/Amazon-HealthLake.svg',
  'aws/service/Machine-Learning/64/Amazon-Kendra.svg',
  'aws/service/Machine-Learning/64/Amazon-Lex.svg',
  'aws/service/Machine-Learning/64/Amazon-Lookout-for-Equipment.svg',
  'aws/service/Machine-Learning/64/Amazon-Lookout-for-Metrics.svg',
  'aws/service/Machine-Learning/64/Amazon-Lookout-for-Vision.svg',
  'aws/service/Machine-Learning/64/Amazon-Monitron.svg',
  'aws/service/Machine-Learning/64/Amazon-Omics.svg',
  'aws/service/Machine-Learning/64/Amazon-Personalize.svg',
  'aws/service/Machine-Learning/64/Amazon-Polly.svg',
  'aws/service/Machine-Learning/64/Amazon-Rekognition.svg',
  'aws/service/Machine-Learning/64/Amazon-SageMaker-Ground-Truth.svg',
  'aws/service/Machine-Learning/64/Amazon-SageMaker-Studio-Lab.svg',
  'aws/service/Machine-Learning/64/Amazon-SageMaker.svg',
  'aws/service/Machine-Learning/64/Amazon-Textract.svg',
  'aws/service/Machine-Learning/64/Amazon-Transcribe.svg',
  'aws/service/Machine-Learning/64/Amazon-Translate.svg',
  'aws/service/Machine-Learning/64/Apache-MXNet-on-AWS.svg',
  'aws/service/Machine-Learning/64/TensorFlow-on-AWS.svg',
  'aws/service/Machine-Learning/64/TorchServe.svg',
  'aws/service/Management-Governance/64/AWS-AppConfig.svg',
  'aws/service/Management-Governance/64/AWS-Application-Auto-Scaling.svg',
  'aws/service/Management-Governance/64/AWS-Auto-Scaling.svg',
  'aws/service/Management-Governance/64/AWS-Backint-Agent.svg',
  'aws/service/Management-Governance/64/AWS-Chatbot.svg',
  'aws/service/Management-Governance/64/AWS-CloudFormation.svg',
  'aws/service/Management-Governance/64/AWS-CloudTrail.svg',
  'aws/service/Management-Governance/64/AWS-Config.svg',
  'aws/service/Management-Governance/64/AWS-Control-Tower.svg',
  'aws/service/Management-Governance/64/AWS-Distro-for-OpenTelemetry.svg',
  'aws/service/Management-Governance/64/AWS-Fault-Injection-Simulator.svg',
  'aws/service/Management-Governance/64/AWS-Health-Dashboard.svg',
  'aws/service/Management-Governance/64/AWS-Launch-Wizard.svg',
  'aws/service/Management-Governance/64/AWS-License-Manager.svg',
  'aws/service/Management-Governance/64/AWS-Management-Console.svg',
  'aws/service/Management-Governance/64/AWS-OpsWorks.svg',
  'aws/service/Management-Governance/64/AWS-Organizations.svg',
  'aws/service/Management-Governance/64/AWS-Proton.svg',
  'aws/service/Management-Governance/64/AWS-Resilience-Hub.svg',
  'aws/service/Management-Governance/64/AWS-Resource-Explorer.svg',
  'aws/service/Management-Governance/64/AWS-Service-Catalog.svg',
  'aws/service/Management-Governance/64/AWS-Service-Management-Connector.svg',
  'aws/service/Management-Governance/64/AWS-Systems-Manager.svg',
  'aws/service/Management-Governance/64/AWS-Telco-Network-Builder.svg',
  'aws/service/Management-Governance/64/AWS-Trusted-Advisor.svg',
  'aws/service/Management-Governance/64/AWS-Well-Architected-Tool.svg',
  'aws/service/Management-Governance/64/Amazon-CloudWatch.svg',
  'aws/service/Management-Governance/64/Amazon-Managed-Grafana.svg',
  'aws/service/Management-Governance/64/Amazon-Managed-Service-for-Prometheus.svg',
  'aws/service/Media-Services/64/AWS-Elemental-Appliances-&-Software.svg',
  'aws/service/Media-Services/64/AWS-Elemental-Conductor.svg',
  'aws/service/Media-Services/64/AWS-Elemental-Delta.svg',
  'aws/service/Media-Services/64/AWS-Elemental-Link.svg',
  'aws/service/Media-Services/64/AWS-Elemental-Live.svg',
  'aws/service/Media-Services/64/AWS-Elemental-MediaConnect.svg',
  'aws/service/Media-Services/64/AWS-Elemental-MediaConvert.svg',
  'aws/service/Media-Services/64/AWS-Elemental-MediaLive.svg',
  'aws/service/Media-Services/64/AWS-Elemental-MediaPackage.svg',
  'aws/service/Media-Services/64/AWS-Elemental-MediaStore.svg',
  'aws/service/Media-Services/64/AWS-Elemental-MediaTailor.svg',
  'aws/service/Media-Services/64/AWS-Elemental-Server.svg',
  'aws/service/Media-Services/64/Amazon-Elastic-Transcoder.svg',
  'aws/service/Media-Services/64/Amazon-Interactive-Video-Service.svg',
  'aws/service/Media-Services/64/Amazon-Kinesis-Video-Streams.svg',
  'aws/service/Media-Services/64/Amazon-Nimble-Studio.svg',
  'aws/service/Migration-Transfer/64/AWS-Application-Discovery-Service.svg',
  'aws/service/Migration-Transfer/64/AWS-Application-Migration-Service.svg',
  'aws/service/Migration-Transfer/64/AWS-DataSync.svg',
  'aws/service/Migration-Transfer/64/AWS-Mainframe-Modernization.svg',
  'aws/service/Migration-Transfer/64/AWS-Migration-Evaluator.svg',
  'aws/service/Migration-Transfer/64/AWS-Migration-Hub.svg',
  'aws/service/Migration-Transfer/64/AWS-Transfer-Family.svg',
  'aws/service/Networking-Content-Delivery/64/AWS-App-Mesh.svg',
  'aws/service/Networking-Content-Delivery/64/AWS-Client-VPN.svg',
  'aws/service/Networking-Content-Delivery/64/AWS-Cloud-Map.svg',
  'aws/service/Networking-Content-Delivery/64/AWS-Cloud-WAN.svg',
  'aws/service/Networking-Content-Delivery/64/AWS-Direct-Connect.svg',
  'aws/service/Networking-Content-Delivery/64/AWS-Global-Accelerator.svg',
  'aws/service/Networking-Content-Delivery/64/AWS-Private-5G.svg',
  'aws/service/Networking-Content-Delivery/64/AWS-PrivateLink.svg',
  'aws/service/Networking-Content-Delivery/64/AWS-Site-to-Site-VPN.svg',
  'aws/service/Networking-Content-Delivery/64/AWS-Transit-Gateway.svg',
  'aws/service/Networking-Content-Delivery/64/AWS-Verified-Access.svg',
  'aws/service/Networking-Content-Delivery/64/Amazon-CloudFront.svg',
  'aws/service/Networking-Content-Delivery/64/Amazon-Route-53.svg',
  'aws/service/Networking-Content-Delivery/64/Amazon-VPC-Lattice.svg',
  'aws/service/Networking-Content-Delivery/64/Amazon-Virtual-Private-Cloud.svg',
  'aws/service/Networking-Content-Delivery/64/Elastic-Load-Balancing.svg',
  'aws/service/Quantum-Technologies/64/Amazon-Braket.svg',
  'aws/service/Robotics/64/AWS-RoboMaker.svg',
  'aws/service/Satellite/64/AWS-Ground-Station.svg',
  'aws/service/Security-Identity-Compliance/64/AWS-Artifact.svg',
  'aws/service/Security-Identity-Compliance/64/AWS-Audit-Manager.svg',
  'aws/service/Security-Identity-Compliance/64/AWS-Certificate-Manager.svg',
  'aws/service/Security-Identity-Compliance/64/AWS-CloudHSM.svg',
  'aws/service/Security-Identity-Compliance/64/AWS-Directory-Service.svg',
  'aws/service/Security-Identity-Compliance/64/AWS-Firewall-Manager.svg',
  'aws/service/Security-Identity-Compliance/64/AWS-IAM-Identity-Center.svg',
  'aws/service/Security-Identity-Compliance/64/AWS-Identity-and-Access-Management.svg',
  'aws/service/Security-Identity-Compliance/64/AWS-Key-Management-Service.svg',
  'aws/service/Security-Identity-Compliance/64/AWS-Network-Firewall.svg',
  'aws/service/Security-Identity-Compliance/64/AWS-Private-Certificate-Authority.svg',
  'aws/service/Security-Identity-Compliance/64/AWS-Resource-Access-Manager.svg',
  'aws/service/Security-Identity-Compliance/64/AWS-Secrets-Manager.svg',
  'aws/service/Security-Identity-Compliance/64/AWS-Security-Hub.svg',
  'aws/service/Security-Identity-Compliance/64/AWS-Shield.svg',
  'aws/service/Security-Identity-Compliance/64/AWS-Signer.svg',
  'aws/service/Security-Identity-Compliance/64/AWS-WAF.svg',
  'aws/service/Security-Identity-Compliance/64/Amazon-Cloud-Directory.svg',
  'aws/service/Security-Identity-Compliance/64/Amazon-Cognito.svg',
  'aws/service/Security-Identity-Compliance/64/Amazon-Detective.svg',
  'aws/service/Security-Identity-Compliance/64/Amazon-GuardDuty.svg',
  'aws/service/Security-Identity-Compliance/64/Amazon-Inspector.svg',
  'aws/service/Security-Identity-Compliance/64/Amazon-Macie.svg',
  'aws/service/Security-Identity-Compliance/64/Amazon-Security-Lake.svg',
  'aws/service/Security-Identity-Compliance/64/Amazon-Verified-Permissions.svg',
  'aws/service/Storage/64/AWS-Backup.svg',
  'aws/service/Storage/64/AWS-Elastic-Disaster-Recovery.svg',
  'aws/service/Storage/64/AWS-Snowball-Edge.svg',
  'aws/service/Storage/64/AWS-Snowball.svg',
  'aws/service/Storage/64/AWS-Snowcone.svg',
  'aws/service/Storage/64/AWS-Snowmobile.svg',
  'aws/service/Storage/64/AWS-Storage-Gateway.svg',
  'aws/service/Storage/64/Amazon-EFS.svg',
  'aws/service/Storage/64/Amazon-Elastic-Block-Store.svg',
  'aws/service/Storage/64/Amazon-FSx-for-Lustre.svg',
  'aws/service/Storage/64/Amazon-FSx-for-NetApp-ONTAP.svg',
  'aws/service/Storage/64/Amazon-FSx-for-OpenZFS.svg',
  'aws/service/Storage/64/Amazon-FSx-for-WFS.svg',
  'aws/service/Storage/64/Amazon-FSx.svg',
  'aws/service/Storage/64/Amazon-File-Cache.svg',
  'aws/service/Storage/64/Amazon-S3-on-Outposts.svg',
  'aws/service/Storage/64/Amazon-Simple-Storage-Service-Glacier.svg',
  'aws/service/Storage/64/Amazon-Simple-Storage-Service.svg',
];

const GCP_PATHS = [
  'gcp/access_context_manager/access_context_manager.svg',
  'gcp/administration/administration.svg',
  'gcp/advanced_agent_modeling/advanced_agent_modeling.svg',
  'gcp/advanced_solutions_lab/advanced_solutions_lab.svg',
  'gcp/agent_assist/agent_assist.svg',
  'gcp/ai_hub/ai_hub.svg',
  'gcp/ai_platform/ai_platform.svg',
  'gcp/ai_platform_unified/ai_platform_unified.svg',
  'gcp/analytics_hub/analytics_hub.svg',
  'gcp/anthos/anthos.svg',
  'gcp/anthos_config_management/anthos_config_management.svg',
  'gcp/anthos_service_mesh/anthos_service_mesh.svg',
  'gcp/api/api.svg',
  'gcp/api_analytics/api_analytics.svg',
  'gcp/api_monetization/api_monetization.svg',
  'gcp/apigee_api_platform/apigee_api_platform.svg',
  'gcp/apigee_sense/apigee_sense.svg',
  'gcp/app_engine/app_engine.svg',
  'gcp/artifact_registry/artifact_registry.svg',
  'gcp/asset_inventory/asset_inventory.svg',
  'gcp/assured_workloads/assured_workloads.svg',
  'gcp/automl/automl.svg',
  'gcp/automl_natural_language/automl_natural_language.svg',
  'gcp/automl_tables/automl_tables.svg',
  'gcp/automl_translation/automl_translation.svg',
  'gcp/automl_video_intelligence/automl_video_intelligence.svg',
  'gcp/automl_vision/automl_vision.svg',
  'gcp/bare_metal_solutions/bare_metal_solutions.svg',
  'gcp/batch/batch.svg',
  'gcp/beyondcorp/beyondcorp.svg',
  'gcp/bigquery/bigquery.svg',
  'gcp/bigtable/bigtable.svg',
  'gcp/billing/billing.svg',
  'gcp/binary_authorization/binary_authorization.svg',
  'gcp/catalog/catalog.svg',
  'gcp/certificate_authority_service/certificate_authority_service.svg',
  'gcp/certificate_manager/certificate_manager.svg',
  'gcp/cloud_api_gateway/cloud_api_gateway.svg',
  'gcp/cloud_apis/cloud_apis.svg',
  'gcp/cloud_armor/cloud_armor.svg',
  'gcp/cloud_asset_inventory/cloud_asset_inventory.svg',
  'gcp/cloud_audit_logs/cloud_audit_logs.svg',
  'gcp/cloud_build/cloud_build.svg',
  'gcp/cloud_cdn/cloud_cdn.svg',
  'gcp/cloud_code/cloud_code.svg',
  'gcp/cloud_composer/cloud_composer.svg',
  'gcp/cloud_data_fusion/cloud_data_fusion.svg',
  'gcp/cloud_deploy/cloud_deploy.svg',
  'gcp/cloud_deployment_manager/cloud_deployment_manager.svg',
  'gcp/cloud_dns/cloud_dns.svg',
  'gcp/cloud_domains/cloud_domains.svg',
  'gcp/cloud_ekm/cloud_ekm.svg',
  'gcp/cloud_endpoints/cloud_endpoints.svg',
  'gcp/cloud_external_ip_addresses/cloud_external_ip_addresses.svg',
  'gcp/cloud_firewall_rules/cloud_firewall_rules.svg',
  'gcp/cloud_for_marketing/cloud_for_marketing.svg',
  'gcp/cloud_functions/cloud_functions.svg',
  'gcp/cloud_generic/cloud_generic.svg',
  'gcp/cloud_gpu/cloud_gpu.svg',
  'gcp/cloud_healthcare_api/cloud_healthcare_api.svg',
  'gcp/cloud_healthcare_marketplace/cloud_healthcare_marketplace.svg',
  'gcp/cloud_hsm/cloud_hsm.svg',
  'gcp/cloud_ids/cloud_ids.svg',
  'gcp/cloud_inference_api/cloud_inference_api.svg',
  'gcp/cloud_interconnect/cloud_interconnect.svg',
  'gcp/cloud_jobs_api/cloud_jobs_api.svg',
  'gcp/cloud_load_balancing/cloud_load_balancing.svg',
  'gcp/cloud_logging/cloud_logging.svg',
  'gcp/cloud_media_edge/cloud_media_edge.svg',
  'gcp/cloud_monitoring/cloud_monitoring.svg',
  'gcp/cloud_nat/cloud_nat.svg',
  'gcp/cloud_natural_language_api/cloud_natural_language_api.svg',
  'gcp/cloud_network/cloud_network.svg',
  'gcp/cloud_ops/cloud_ops.svg',
  'gcp/cloud_optimization_ai/cloud_optimization_ai.svg',
  'gcp/cloud_optimization_ai_-_fleet_routing_api/cloud_optimization_ai_-_fleet_routing_api.svg',
  'gcp/cloud_router/cloud_router.svg',
  'gcp/cloud_routes/cloud_routes.svg',
  'gcp/cloud_run/cloud_run.svg',
  'gcp/cloud_run_for_anthos/cloud_run_for_anthos.svg',
  'gcp/cloud_scheduler/cloud_scheduler.svg',
  'gcp/cloud_security_scanner/cloud_security_scanner.svg',
  'gcp/cloud_shell/cloud_shell.svg',
  'gcp/cloud_spanner/cloud_spanner.svg',
  'gcp/cloud_sql/cloud_sql.svg',
  'gcp/cloud_storage/cloud_storage.svg',
  'gcp/cloud_tasks/cloud_tasks.svg',
  'gcp/cloud_test_lab/cloud_test_lab.svg',
  'gcp/cloud_tpu/cloud_tpu.svg',
  'gcp/cloud_translation_api/cloud_translation_api.svg',
  'gcp/cloud_vision_api/cloud_vision_api.svg',
  'gcp/cloud_vpn/cloud_vpn.svg',
  'gcp/compute_engine/compute_engine.svg',
  'gcp/configuration_management/configuration_management.svg',
  'gcp/connectivity_test/connectivity_test.svg',
  'gcp/connectors/connectors.svg',
  'gcp/contact_center_ai/contact_center_ai.svg',
  'gcp/container_optimized_os/container_optimized_os.svg',
  'gcp/container_registry/container_registry.svg',
  'gcp/data_catalog/data_catalog.svg',
  'gcp/data_labeling/data_labeling.svg',
  'gcp/data_layers/data_layers.svg',
  'gcp/data_loss_prevention_api/data_loss_prevention_api.svg',
  'gcp/data_qna/data_qna.svg',
  'gcp/data_studio/data_studio.svg',
  'gcp/data_transfer/data_transfer.svg',
  'gcp/database_migration_service/database_migration_service.svg',
  'gcp/dataflow/dataflow.svg',
  'gcp/datalab/datalab.svg',
  'gcp/dataplex/dataplex.svg',
  'gcp/datapol/datapol.svg',
  'gcp/dataprep/dataprep.svg',
  'gcp/dataproc/dataproc.svg',
  'gcp/dataproc_metastore/dataproc_metastore.svg',
  'gcp/datashare/datashare.svg',
  'gcp/datastore/datastore.svg',
  'gcp/datastream/datastream.svg',
  'gcp/debugger/debugger.svg',
  'gcp/developer_portal/developer_portal.svg',
  'gcp/dialogflow/dialogflow.svg',
  'gcp/dialogflow_cx/dialogflow_cx.svg',
  'gcp/dialogflow_insights/dialogflow_insights.svg',
  'gcp/document_ai/document_ai.svg',
  'gcp/early_access_center/early_access_center.svg',
  'gcp/error_reporting/error_reporting.svg',
  'gcp/eventarc/eventarc.svg',
  'gcp/filestore/filestore.svg',
  'gcp/financial_services_marketplace/financial_services_marketplace.svg',
  'gcp/firestore/firestore.svg',
  'gcp/fleet_engine/fleet_engine.svg',
  'gcp/free_trial/free_trial.svg',
  'gcp/game_servers/game_servers.svg',
  'gcp/gce_systems_management/gce_systems_management.svg',
  'gcp/genomics/genomics.svg',
  'gcp/gke_on-prem/gke_on-prem.svg',
  'gcp/google_cloud_marketplace/google_cloud_marketplace.svg',
  'gcp/google_kubernetes_engine/google_kubernetes_engine.svg',
  'gcp/google_maps_platform/google_maps_platform.svg',
  'gcp/healthcare_nlp_api/healthcare_nlp_api.svg',
  'gcp/home/home.svg',
  'gcp/identity-aware_proxy/identity-aware_proxy.svg',
  'gcp/identity_and_access_management/identity_and_access_management.svg',
  'gcp/identity_platform/identity_platform.svg',
  'gcp/iot_core/iot_core.svg',
  'gcp/iot_edge/iot_edge.svg',
  'gcp/key_access_justifications/key_access_justifications.svg',
  'gcp/key_management_service/key_management_service.svg',
  'gcp/kuberun/kuberun.svg',
  'gcp/launcher/launcher.svg',
  'gcp/local_ssd/local_ssd.svg',
  'gcp/looker/looker.svg',
  'gcp/managed_service_for_microsoft_active_directory/managed_service_for_microsoft_active_directory.svg',
  'gcp/media_translation_api/media_translation_api.svg',
  'gcp/memorystore/memorystore.svg',
  'gcp/migrate_for_anthos/migrate_for_anthos.svg',
  'gcp/migrate_for_compute_engine/migrate_for_compute_engine.svg',
  'gcp/my_cloud/my_cloud.svg',
  'gcp/network_connectivity_center/network_connectivity_center.svg',
  'gcp/network_intelligence_center/network_intelligence_center.svg',
  'gcp/network_security/network_security.svg',
  'gcp/network_tiers/network_tiers.svg',
  'gcp/network_topology/network_topology.svg',
  'gcp/onboarding/onboarding.svg',
  'gcp/os_configuration_management/os_configuration_management.svg',
  'gcp/os_inventory_management/os_inventory_management.svg',
  'gcp/os_patch_management/os_patch_management.svg',
  'gcp/partner_interconnect/partner_interconnect.svg',
  'gcp/partner_portal/partner_portal.svg',
  'gcp/performance_dashboard/performance_dashboard.svg',
  'gcp/permissions/permissions.svg',
  'gcp/persistent_disk/persistent_disk.svg',
  'gcp/phishing_protection/phishing_protection.svg',
  'gcp/policy_analyzer/policy_analyzer.svg',
  'gcp/premium_network_tier/premium_network_tier.svg',
  'gcp/private_connectivity/private_connectivity.svg',
  'gcp/private_service_connect/private_service_connect.svg',
  'gcp/producer_portal/producer_portal.svg',
  'gcp/profiler/profiler.svg',
  'gcp/project/project.svg',
  'gcp/pubsub/pubsub.svg',
  'gcp/quantum_engine/quantum_engine.svg',
  'gcp/quotas/quotas.svg',
  'gcp/real-world_insights/real-world_insights.svg',
  'gcp/recommendations_ai/recommendations_ai.svg',
  'gcp/release_notes/release_notes.svg',
  'gcp/retail_api/retail_api.svg',
  'gcp/risk_manager/risk_manager.svg',
  'gcp/runtime_config/runtime_config.svg',
  'gcp/secret_manager/secret_manager.svg',
  'gcp/security/security.svg',
  'gcp/security_command_center/security_command_center.svg',
  'gcp/security_health_advisor/security_health_advisor.svg',
  'gcp/security_key_enforcement/security_key_enforcement.svg',
  'gcp/service_discovery/service_discovery.svg',
  'gcp/speech-to-text/speech-to-text.svg',
  'gcp/stackdriver/stackdriver.svg',
  'gcp/standard_network_tier/standard_network_tier.svg',
  'gcp/stream_suite/stream_suite.svg',
  'gcp/support/support.svg',
  'gcp/tensorflow_enterprise/tensorflow_enterprise.svg',
  'gcp/text-to-speech/text-to-speech.svg',
  'gcp/tools_for_powershell/tools_for_powershell.svg',
  'gcp/trace/trace.svg',
  'gcp/traffic_director/traffic_director.svg',
  'gcp/transfer/transfer.svg',
  'gcp/transfer_appliance/transfer_appliance.svg',
  'gcp/user_preferences/user_preferences.svg',
  'gcp/vertexai/vertexai.svg',
  'gcp/video_intelligence_api/video_intelligence_api.svg',
  'gcp/virtual_private_cloud/virtual_private_cloud.svg',
  'gcp/visual_inspection/visual_inspection.svg',
  'gcp/vmware_engine/vmware_engine.svg',
  'gcp/web_risk/web_risk.svg',
  'gcp/web_security_scanner/web_security_scanner.svg',
  'gcp/workflows/workflows.svg',
  'gcp/workload_identity_pool/workload_identity_pool.svg',
];

const LOOKUP = new Map<string, IconEntry>();
const ALL_KEYS: string[] = [];

// 1. Initialize static manually declared keys
for (const [key, entry] of Object.entries(ICON_REGISTRY)) {
  const norm = normalize(key);
  LOOKUP.set(norm, entry);
  ALL_KEYS.push(key);
}

// Helper to register dynamic keys avoiding duplicates
const registerKey = (k: string, entry: IconEntry) => {
  const norm = normalize(k);
  if (!LOOKUP.has(norm)) {
    LOOKUP.set(norm, entry);
    ALL_KEYS.push(k);
  }
};

// 2. Register dynamic AWS paths
for (const p of AWS_PATHS) {
  const parts = p.split('/');
  const filename = parts[parts.length - 1];
  const base = filename.substring(0, filename.length - 4); // remove .svg
  const cleanName = base.replace(/[-_]+/g, ' ');
  const entry: IconEntry = { source: 'cloud', slug: p };

  registerKey(cleanName, entry);

  if (cleanName.startsWith('AWS ')) {
    registerKey(cleanName.replace(/^AWS\s+/, 'Amazon '), entry);
    registerKey(cleanName.replace(/^AWS\s+/, ''), entry);
  } else if (cleanName.startsWith('Amazon ')) {
    registerKey(cleanName.replace(/^Amazon\s+/, 'AWS '), entry);
    registerKey(cleanName.replace(/^Amazon\s+/, ''), entry);
  }
}

// 3. Register dynamic GCP paths
for (const p of GCP_PATHS) {
  const parts = p.split('/');
  const filename = parts[parts.length - 1];
  const base = filename.substring(0, filename.length - 4); // remove .svg
  const cleanName = base.replace(/[-_]+/g, ' ');
  const titleName = cleanName.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
  const entry: IconEntry = { source: 'cloud', slug: p };

  registerKey(titleName, entry);
  registerKey(`GCP ${titleName}`, entry);
  registerKey(`Google Cloud ${titleName}`, entry);
  registerKey(`Google ${titleName}`, entry);
}

// Sort all registered keys by length descending to match longest/most specific keys first
const SORTED_KEYS = [...ALL_KEYS].sort((a, b) => b.length - a.length);

export function getIconUrl(label: string): string | null {
  const normLabel = normalize(label);
  if (!normLabel) return null;

  // 1. Try exact normalized match first
  const exactEntry = LOOKUP.get(normLabel);
  if (exactEntry) return buildIconUrl(exactEntry);

  // 2. Try matching if registry key is a substring of the label (longer keys matched first)
  for (const key of SORTED_KEYS) {
    const normKey = normalize(key);
    if (normKey.length > 2 && normLabel.includes(normKey)) {
      const entry = LOOKUP.get(normKey);
      if (entry) return buildIconUrl(entry);
    }
  }

  // 3. Try matching if label is a substring of registry key
  for (const key of SORTED_KEYS) {
    const normKey = normalize(key);
    if (normLabel.length > 2 && normKey.includes(normLabel)) {
      const entry = LOOKUP.get(normKey);
      if (entry) return buildIconUrl(entry);
    }
  }

  // 4. Fallback for very short keys (exact or bounded word check)
  for (const key of SORTED_KEYS) {
    const normKey = normalize(key);
    if (normLabel.includes(normKey)) {
      const labelWords = label.toLowerCase().split(/[^a-z0-9]+/);
      const keyWords = key.toLowerCase().split(/[^a-z0-9]+/);
      if (labelWords.some(w => keyWords.includes(w))) {
        const entry = LOOKUP.get(normKey);
        if (entry) return buildIconUrl(entry);
      }
    }
  }

  return null;
}
