type IconSource = 'devicon' | 'simpleicons' | 'local' | 'svgl' | 'selfhst' | 'cloud';

interface IconEntry {
  source: IconSource;
  slug: string;
  variant?: string;
}

export const ICON_REGISTRY: Record<string, IconEntry> = {
  // Dev tools (devicon CDN)
  'Traefik': { source: 'selfhst', slug: 'traefik' },
  'SST': { source: 'svgl', slug: 'sst' },
  'Serverless Framework': { source: 'simpleicons', slug: 'serverless' },
  'OpenFaaS': { source: 'simpleicons', slug: 'openfaas' },
  'Knative': { source: 'simpleicons', slug: 'knative' },
  'Fauna': { source: 'devicon', slug: 'faunadb' },
  'Airbyte': { source: 'simpleicons', slug: 'airbyte' },
  'dbt': { source: 'simpleicons', slug: 'dbt' },
  'Prefect': { source: 'simpleicons', slug: 'prefect' },
  'Dagster': { source: 'selfhst', slug: 'dagster' },
  'Apache Airflow': { source: 'devicon', slug: 'apacheairflow' },
  'WorkOS': { source: 'svgl', slug: 'workos' },
  'Ory': { source: 'devicon', slug: 'ory' },
  'Logto': { source: 'selfhst', slug: 'logto' },
  'SigNoz': { source: 'selfhst', slug: 'signoz' },
  'Logstash': { source: 'devicon', slug: 'logstash' },
  'Fluentd': { source: 'simpleicons', slug: 'fluentd' },
  'Fluent Bit': { source: 'simpleicons', slug: 'fluentbit' },
  'Graylog': { source: 'selfhst', slug: 'graylog' },
  'Splunk': { source: 'selfhst', slug: 'splunk' },
  'New Relic': { source: 'devicon', slug: 'newrelic' },
  'Dynatrace': { source: 'devicon', slug: 'dynatrace' },
  'Istio': { source: 'simpleicons', slug: 'istio' },
  'Linkerd': { source: 'simpleicons', slug: 'linkerd' },
  'EMQX': { source: 'selfhst', slug: 'emqx' },
  'HiveMQ': { source: 'selfhst', slug: 'hivemq' },
  'Eclipse Mosquitto': { source: 'selfhst', slug: 'mosquitto' },
  'Mattermost': { source: 'selfhst', slug: 'mattermost' },
  'Zulip': { source: 'selfhst', slug: 'zulip' },
  'Matrix': { source: 'selfhst', slug: 'matrix' },
  'Microsoft Teams': { source: 'selfhst', slug: 'microsoft-teams' },
  'Apache Avro': { source: 'simpleicons', slug: 'apacheavro' },
  'Apache Parquet': { source: 'simpleicons', slug: 'apacheparquet' },

  'Prettier': { source: 'svgl', slug: 'prettier-icon-dark' },
  'ESLint': { source: 'svgl', slug: 'eslint-icon-dark' },
  'Vitest': { source: 'svgl', slug: 'vitest' },
  'Playwright': { source: 'svgl', slug: 'playwright' },
  'Cypress': { source: 'svgl', slug: 'cypress' },
  'Puppeteer': { source: 'devicon', slug: 'puppeteer' },
  'Webpack': { source: 'devicon', slug: 'webpack' },
  'Rollup': { source: 'devicon', slug: 'rollup' },
  'Babel': { source: 'svgl', slug: 'babel' },
  'PostCSS': { source: 'svgl', slug: 'postcss' },
  'Radix UI': { source: 'svgl', slug: 'radix-ui_dark' },
  'Chakra UI': { source: 'svgl', slug: 'chakra-ui' },
  'Shadcn UI': { source: 'svgl', slug: 'shadcn-ui_dark' },
  'Mantine': { source: 'svgl', slug: 'mantine' },
  'Material UI': { source: 'svgl', slug: 'materialui' },
  'Webflow': { source: 'svgl', slug: 'webflow' },
  'Gatsby': { source: 'selfhst', slug: 'gatsby' },
  'Hugo': { source: 'selfhst', slug: 'hugo' },
  'Jekyll': { source: 'selfhst', slug: 'jekyll' },
  'Eleventy': { source: 'selfhst', slug: 'eleventy' },
  'Nuxt.js': { source: 'selfhst', slug: 'nuxt' },
  'Presto': { source: 'simpleicons', slug: 'presto' },
  'Trino': { source: 'simpleicons', slug: 'trino' },
  'ScyllaDB': { source: 'simpleicons', slug: 'scylladb' },
  'ArangoDB': { source: 'simpleicons', slug: 'arangodb' },
  'MQTT': { source: 'selfhst', slug: 'mqtt' },
  'ZeroMQ': { source: 'simpleicons', slug: 'zeromq' },
  'Crystal': { source: 'devicon', slug: 'crystal' },
  'Nim': { source: 'devicon', slug: 'nim' },
  'Perl': { source: 'devicon', slug: 'perl' },
  'F#': { source: 'devicon', slug: 'fsharp' },
  'Salesforce': { source: 'selfhst', slug: 'salesforce' },
  'HubSpot': { source: 'simpleicons', slug: 'hubspot' },
  'Zendesk': { source: 'simpleicons', slug: 'zendesk' },
  'Intercom': { source: 'simpleicons', slug: 'intercom' },
  'Mixpanel': { source: 'simpleicons', slug: 'mixpanel' },
  'Hotjar': { source: 'simpleicons', slug: 'hotjar' },

  'Weaviate': { source: 'selfhst', slug: 'weaviate' },
  'WebSockets': { source: 'selfhst', slug: 'websocket' },
  'HAProxy': { source: 'selfhst', slug: 'haproxy' },
  'Authelia': { source: 'selfhst', slug: 'authelia' },
  'MinIO': { source: 'selfhst', slug: 'minio' },
  'Plausible': { source: 'selfhst', slug: 'plausible' },
  'Umami': { source: 'selfhst', slug: 'umami' },
  'Uptime Kuma': { source: 'selfhst', slug: 'uptime-kuma' },
  'Nextcloud': { source: 'selfhst', slug: 'nextcloud' },
  'Syncthing': { source: 'selfhst', slug: 'syncthing' },
  'Dex Auth': { source: 'selfhst', slug: 'dex-auth' },
  'AdGuard Home': { source: 'selfhst', slug: 'adguard-home' },
  'Directus': { source: 'selfhst', slug: 'directus' },
  'Ghostty': { source: 'selfhst', slug: 'ghostty' },
  'Gitea': { source: 'selfhst', slug: 'gitea' },
  'Home Assistant': { source: 'selfhst', slug: 'home-assistant' },
  'Jellyfin': { source: 'selfhst', slug: 'jellyfin' },
  'Nginx Proxy Manager': { source: 'selfhst', slug: 'nginx-proxy-manager' },
  'Strapi': { source: 'selfhst', slug: 'strapi' },
  'Vaultwarden': { source: 'selfhst', slug: 'vaultwarden' },
  'WordPress': { source: 'selfhst', slug: 'wordpress' },
  'Appwrite': { source: 'selfhst', slug: 'appwrite' },
  'Baserow': { source: 'selfhst', slug: 'baserow' },
  'Flowise': { source: 'selfhst', slug: 'flowise' },
  'Metabase': { source: 'selfhst', slug: 'metabase' },
  'n8n': { source: 'selfhst', slug: 'n8n' },
  'NocoDB': { source: 'selfhst', slug: 'nocodb' },
  'Open WebUI': { source: 'selfhst', slug: 'open-webui' },
  'PocketBase': { source: 'selfhst', slug: 'pocketbase' },

  'Git': { source: 'svgl', slug: 'git' },
  'Preact': { source: 'svgl', slug: 'preact' },
  'Lit': { source: 'svgl', slug: 'lit' },
  'React Native': { source: 'svgl', slug: 'react_dark' },
  'Flutter': { source: 'svgl', slug: 'flutter' },
  'Electron': { source: 'svgl', slug: 'electron' },
  'Tauri': { source: 'svgl', slug: 'tauri' },
  'Expo': { source: 'svgl', slug: 'expo' },
  'Sass': { source: 'svgl', slug: 'sass' },
  'Bootstrap': { source: 'svgl', slug: 'bootstrap' },
  'Framer Motion': { source: 'svgl', slug: 'framer_dark' },
  'CockroachDB': { source: 'simpleicons', slug: 'cockroachlabs' },
  'Snowflake': { source: 'simpleicons', slug: 'snowflake' },
  'Databricks': { source: 'simpleicons', slug: 'databricks' },
  'Apache Spark': { source: 'devicon', slug: 'apachespark' },
  'OpenSearch': { source: 'simpleicons', slug: 'opensearch' },
  'Memcached': { source: 'devicon', slug: 'memcached' },
  'Netlify': { source: 'svgl', slug: 'netlify' },
  'DigitalOcean': { source: 'svgl', slug: 'digitalocean' },
  'Fastly': { source: 'simpleicons', slug: 'fastly' },
  'Akamai': { source: 'simpleicons', slug: 'akamai' },
  'Linode': { source: 'simpleicons', slug: 'linode' },
  'GitHub': { source: 'svgl', slug: 'github_dark' },
  'Bitbucket': { source: 'devicon', slug: 'bitbucket' },
  'Rancher': { source: 'devicon', slug: 'rancher' },
  'OpenShift': { source: 'simpleicons', slug: 'redhatopenshift' },
  'Portainer': { source: 'devicon', slug: 'portainer' },
  'Caddy': { source: 'simpleicons', slug: 'caddy' },
  'Authentik': { source: 'simpleicons', slug: 'authentik' },
  'Teleport': { source: 'devicon', slug: 'teleport' },
  'Jira': { source: 'devicon', slug: 'jira' },
  'Notion': { source: 'svgl', slug: 'notion' },
  'Linear': { source: 'svgl', slug: 'linear' },
  'Trello': { source: 'svgl', slug: 'trello' },
  'Koa': { source: 'simpleicons', slug: 'koa' },
  'TypeORM': { source: 'svgl', slug: 'typeorm' },
  'Sequelize': { source: 'svgl', slug: 'sequelize' },
  'Mongoose': { source: 'devicon', slug: 'mongoose' },

  'Zig': { source: 'svgl', slug: 'zig' },
  'Elixir': { source: 'devicon', slug: 'elixir' },
  'Clojure': { source: 'devicon', slug: 'clojure' },
  'Haskell': { source: 'svgl', slug: 'haskell' },
  'Scala': { source: 'svgl', slug: 'scala' },
  'Kotlin': { source: 'svgl', slug: 'kotlin' },
  'Swift': { source: 'svgl', slug: 'swift' },
  'PHP': { source: 'svgl', slug: 'php' },
  'Ruby': { source: 'svgl', slug: 'ruby' },
  'C++': { source: 'svgl', slug: 'c-plusplus' },
  'C#': { source: 'svgl', slug: 'csharp' },
  'Java': { source: 'svgl', slug: 'java' },
  'Dart': { source: 'svgl', slug: 'dart' },
  'Lua': { source: 'svgl', slug: 'lua' },
  'Julia': { source: 'svgl', slug: 'julia' },
  'Astro': { source: 'svgl', slug: 'astro-icon-dark' },
  'SolidJS': { source: 'svgl', slug: 'solidjs' },
  'Remix': { source: 'svgl', slug: 'remix_dark' },
  'Qwik': { source: 'svgl', slug: 'qwik' },
  'Angular': { source: 'svgl', slug: 'angular' },
  'Laravel': { source: 'svgl', slug: 'laravel' },
  'Spring Boot': { source: 'svgl', slug: 'spring' },
  'NestJS': { source: 'svgl', slug: 'nestjs' },
  'Ruby on Rails': { source: 'simpleicons', slug: 'rails' },
  'Flask': { source: 'svgl', slug: 'flask-dark' },
  'Gin': { source: 'simpleicons', slug: 'gin' },
  'Fiber': { source: 'devicon', slug: 'fiber' },
  'Phoenix': { source: 'devicon', slug: 'phoenix' },
  'Actix': { source: 'simpleicons', slug: 'actix' },
  'Cassandra': { source: 'devicon', slug: 'cassandra' },
  'ClickHouse': { source: 'devicon', slug: 'clickhouse' },
  'InfluxDB': { source: 'devicon', slug: 'influxdb' },
  'TimescaleDB': { source: 'simpleicons', slug: 'timescale' },
  'Neo4j': { source: 'devicon', slug: 'neo4j' },
  'Typesense': { source: 'svgl', slug: 'typesense' },
  'Milvus': { source: 'simpleicons', slug: 'milvus' },
  'Qdrant': { source: 'svgl', slug: 'qdrant-icon-dark' },
  'Hasura': { source: 'simpleicons', slug: 'hasura' },
  'SurrealDB': { source: 'svgl', slug: 'surrealdb' },
  'RabbitMQ': { source: 'devicon', slug: 'rabbitmq' },
  'Celery': { source: 'simpleicons', slug: 'celery' },
  'NATS': { source: 'devicon', slug: 'nats' },
  'Ansible': { source: 'devicon', slug: 'ansible' },
  'Terraform': { source: 'svgl', slug: 'terraform' },
  'Pulumi': { source: 'svgl', slug: 'pulumi' },
  'ArgoCD': { source: 'devicon', slug: 'argocd' },
  'Jenkins': { source: 'devicon', slug: 'jenkins' },
  'GitHub Actions': { source: 'devicon', slug: 'githubactions' },
  'GitLab CI': { source: 'svgl', slug: 'gitlab' },
  'Nomad': { source: 'devicon', slug: 'nomad' },
  'Consul': { source: 'devicon', slug: 'consul' },
  'Vault': { source: 'devicon', slug: 'vault' },
  'gRPC': { source: 'devicon', slug: 'grpc' },
  'Kong': { source: 'simpleicons', slug: 'kong' },
  'Envoy': { source: 'devicon', slug: 'envoy' },
  'OpenTelemetry': { source: 'devicon', slug: 'opentelemetry' },
  'Jaeger': { source: 'simpleicons', slug: 'jaeger' },
  'Better Auth': { source: 'svgl', slug: 'better-auth_dark' },
  'Keycloak': { source: 'svgl', slug: 'keycloak' },
  'Firebase Auth': { source: 'svgl', slug: 'firebase' },
  'Okta': { source: 'devicon', slug: 'okta' },
  'Bitwarden': { source: 'svgl', slug: 'bitwarden' },
  'LangChain': { source: 'simpleicons', slug: 'langchain' },
  'Hugging Face': { source: 'svgl', slug: 'hugging_face' },
  'PyTorch': { source: 'devicon', slug: 'pytorch' },
  'Ollama': { source: 'svgl', slug: 'ollama_dark' },
  'Cohere': { source: 'svgl', slug: 'cohere' },
  'Replicate': { source: 'svgl', slug: 'replicate_dark' },
  'Slack': { source: 'svgl', slug: 'slack' },
  'Discord': { source: 'svgl', slug: 'discord' },
  'Telegram': { source: 'svgl', slug: 'telegram' },
  'Loops': { source: 'simpleicons', slug: 'loops' },
  'PayPal': { source: 'svgl', slug: 'paypal' },
  'Shopify': { source: 'svgl', slug: 'shopify' },
  'Mailchimp': { source: 'simpleicons', slug: 'mailchimp' },

  'FastAPI': { source: 'svgl', slug: 'fastapi' },
  'MetaMask': { source: 'svgl', slug: 'metamask' },
  'Next.js': { source: 'svgl', slug: 'nextjs_icon_dark' },
  'React': { source: 'svgl', slug: 'react_dark' },
  'Vue': { source: 'svgl', slug: 'vue' },
  'Svelte': { source: 'svgl', slug: 'svelte' },
  'Bun': { source: 'svgl', slug: 'bun' },
  'Node.js': { source: 'svgl', slug: 'nodejs' },
  'Deno': { source: 'svgl', slug: 'deno' },
  'Go': { source: 'devicon', slug: 'go' },
  'Rust': { source: 'svgl', slug: 'rust' },
  'Python': { source: 'svgl', slug: 'python' },
  'TypeScript': { source: 'svgl', slug: 'typescript' },
  'JavaScript': { source: 'svgl', slug: 'javascript' },
  'PostgreSQL': { source: 'svgl', slug: 'postgresql' },
  'MySQL': { source: 'svgl', slug: 'mysql-icon-dark' },
  'MongoDB': { source: 'svgl', slug: 'mongodb-icon-dark' },
  'Redis': { source: 'svgl', slug: 'redis' },
  'SQLite': { source: 'svgl', slug: 'sqlite' },
  'Docker': { source: 'svgl', slug: 'docker' },
  'Kubernetes': { source: 'svgl', slug: 'kubernetes' },
  'Nginx': { source: 'svgl', slug: 'nginx' },
  'GraphQL': { source: 'svgl', slug: 'graphql' },
  'Prisma': { source: 'svgl', slug: 'prisma' },
  'Vite': { source: 'svgl', slug: 'vite' },
  'Tailwind CSS': { source: 'svgl', slug: 'tailwindcss' },
  'Hono': { source: 'svgl', slug: 'hono' },
  'Fastify': { source: 'svgl', slug: 'fastify' },
  'Express': { source: 'devicon', slug: 'express' },
  'Kafka': { source: 'devicon', slug: 'apachekafka' },
  'Elasticsearch': { source: 'devicon', slug: 'elasticsearch' },

  // Simple Icons
  'Elysia': { source: 'devicon', slug: 'bun' },
  'tRPC': { source: 'svgl', slug: 'trpc' },
  'Zod': { source: 'svgl', slug: 'zod' },
  'Drizzle': { source: 'simpleicons', slug: 'drizzle' },
  'Vercel': { source: 'svgl', slug: 'vercel_dark' },
  'Cloudflare': { source: 'svgl', slug: 'cloudflare' },
  'Cloudflare Workers': { source: 'svgl', slug: 'cloudflare-workers' },
  'Cloudflare R2': { source: 'simpleicons', slug: 'cloudflare' },
  'Cloudflare CDN': { source: 'simpleicons', slug: 'cloudflare' },
  'Neon': { source: 'svgl', slug: 'neon' },
  'PlanetScale': { source: 'svgl', slug: 'planetscale' },
  'Supabase': { source: 'svgl', slug: 'supabase' },
  'Supabase PostgreSQL': { source: 'svgl', slug: 'supabase' },
  'Turso': { source: 'svgl', slug: 'turso-dark' },
  'Upstash': { source: 'svgl', slug: 'upstash' },
  'Stripe': { source: 'svgl', slug: 'stripe' },
  'Resend': { source: 'svgl', slug: 'resend-icon-black' },
  'Mailgun': { source: 'simpleicons', slug: 'mailgun' },
  'SendGrid': { source: 'simpleicons', slug: 'twilio' },
  'Twilio': { source: 'svgl', slug: 'twilio' },
  'GitHub OAuth': { source: 'simpleicons', slug: 'github' },
  'Google OAuth': { source: 'svgl', slug: 'google' },
  'Clerk': { source: 'svgl', slug: 'clerk-icon-dark' },
  'Auth0': { source: 'svgl', slug: 'auth0' },
  'PostHog': { source: 'svgl', slug: 'posthog' },
  'Sentry': { source: 'svgl', slug: 'sentry' },
  'Datadog': { source: 'svgl', slug: 'datadog' },
  'Grafana': { source: 'svgl', slug: 'grafana' },
  'Prometheus': { source: 'simpleicons', slug: 'prometheus' },
  'Railway': { source: 'svgl', slug: 'railway' },
  'Fly.io': { source: 'simpleicons', slug: 'flydotio' },
  'Render': { source: 'simpleicons', slug: 'render' },
  'Heroku': { source: 'svgl', slug: 'heroku' },
  'Algolia': { source: 'svgl', slug: 'algolia' },
  'OpenAI': { source: 'svgl', slug: 'openai_dark' },
  'Anthropic': { source: 'svgl', slug: 'anthropic_black' },
  'Meilisearch': { source: 'simpleicons', slug: 'meilisearch' },
  'Django': { source: 'svgl', slug: 'django' },
  'postgres': { source: 'svgl', slug: 'postgresql' },
  'AI Service (Python)': { source: 'devicon', slug: 'python' },
  'AWS S3': { source: 'cloud', slug: 'aws/service/Storage/64/Amazon-Simple-Storage-Service.svg' },

  // AWS Services
  'AWS Lambda': { source: 'cloud', slug: 'aws/service/Compute/64/AWS-Lambda.svg' },
  'Amazon S3': { source: 'cloud', slug: 'aws/service/Storage/64/Amazon-Simple-Storage-Service.svg' },
  'Amazon RDS': { source: 'cloud', slug: 'aws/service/Database/64/Amazon-RDS.svg' },
  'Amazon DynamoDB': { source: 'cloud', slug: 'aws/service/Database/64/Amazon-DynamoDB.svg' },
  'Amazon SQS': { source: 'cloud', slug: 'aws/service/App-Integration/64/Amazon-Simple-Queue-Service.svg' },
  'Amazon SES': { source: 'cloud', slug: 'aws/service/Business-Applications/64/Amazon-Simple-Email-Service.svg' },
  'Amazon EC2': { source: 'cloud', slug: 'aws/service/Compute/64/Amazon-EC2.svg' },
  'Amazon ECS': { source: 'cloud', slug: 'aws/service/Containers/64/Amazon-Elastic-Container-Service.svg' },
  'Amazon EKS': { source: 'cloud', slug: 'aws/service/Containers/64/Amazon-Elastic-Kubernetes-Service.svg' },
  'Amazon CloudFront': { source: 'cloud', slug: 'aws/service/Networking-Content-Delivery/64/Amazon-CloudFront.svg' },
  'Amazon API Gateway': { source: 'cloud', slug: 'aws/service/App-Integration/64/Amazon-API-Gateway.svg' },
  'Amazon Cognito': { source: 'cloud', slug: 'aws/service/Security-Identity-Compliance/64/Amazon-Cognito.svg' },
  'Amazon Route 53': { source: 'cloud', slug: 'aws/service/Networking-Content-Delivery/64/Amazon-Route-53.svg' },
  'Amazon ElastiCache': { source: 'cloud', slug: 'aws/service/Database/64/Amazon-ElastiCache.svg' },
  'Amazon EventBridge': { source: 'cloud', slug: 'aws/service/App-Integration/64/Amazon-EventBridge.svg' },
  'Amazon SNS': { source: 'cloud', slug: 'aws/service/App-Integration/64/Amazon-Simple-Notification-Service.svg' },
  'Amazon Kinesis': { source: 'cloud', slug: 'aws/service/Analytics/64/Amazon-Kinesis.svg' },
  'AWS Step Functions': { source: 'cloud', slug: 'aws/service/App-Integration/64/AWS-Step-Functions.svg' },
  'AWS Fargate': { source: 'cloud', slug: 'aws/service/Containers/64/AWS-Fargate.svg' },
  'Amazon Aurora': { source: 'cloud', slug: 'aws/service/Database/64/Amazon-Aurora.svg' },
  'AWS Secrets Manager': { source: 'cloud', slug: 'aws/service/Security-Identity-Compliance/64/AWS-Secrets-Manager.svg' },
  'AWS WAF': { source: 'cloud', slug: 'aws/service/Security-Identity-Compliance/64/AWS-WAF.svg' },
  'Amazon VPC': { source: 'cloud', slug: 'aws/service/Networking-Content-Delivery/64/Amazon-Virtual-Private-Cloud.svg' },
  'AWS IAM': { source: 'cloud', slug: 'aws/service/Security-Identity-Compliance/64/AWS-Identity-and-Access-Management.svg' },
  'Amazon CloudWatch': { source: 'cloud', slug: 'aws/service/Management-Governance/64/Amazon-CloudWatch.svg' },
  'Amazon Athena': { source: 'cloud', slug: 'aws/service/Analytics/64/Amazon-Athena.svg' },
  'Amazon Redshift': { source: 'cloud', slug: 'aws/service/Analytics/64/Amazon-Redshift.svg' },
  'Amazon Bedrock': { source: 'simpleicons', slug: 'amazonwebservices' },

  // GCP Services
  'GCP Cloud Run': { source: 'cloud', slug: 'gcp/cloud_run/cloud_run.svg' },
  'GCP Cloud Functions': { source: 'cloud', slug: 'gcp/cloud_functions/cloud_functions.svg' },
  'GCP BigQuery': { source: 'cloud', slug: 'gcp/bigquery/bigquery.svg' },
  'GCP Pub/Sub': { source: 'cloud', slug: 'gcp/pubsub/pubsub.svg' },
  'GCP Cloud Storage': { source: 'cloud', slug: 'gcp/cloud_storage/cloud_storage.svg' },
  'GCP Firebase': { source: 'simpleicons', slug: 'firebase' },
  'GCP Firestore': { source: 'cloud', slug: 'gcp/firestore/firestore.svg' },
  'GCP Cloud SQL': { source: 'cloud', slug: 'gcp/cloud_sql/cloud_sql.svg' },
  'GCP Vertex AI': { source: 'cloud', slug: 'gcp/vertexai/vertexai.svg' },
  'GCP GKE': { source: 'cloud', slug: 'gcp/google_kubernetes_engine/google_kubernetes_engine.svg' },
  'GCP Cloud Armor': { source: 'cloud', slug: 'gcp/cloud_armor/cloud_armor.svg' },
  'GCP Load Balancer': { source: 'cloud', slug: 'gcp/cloud_load_balancing/cloud_load_balancing.svg' },
  'GCP Memorystore': { source: 'cloud', slug: 'gcp/memorystore/memorystore.svg' },
  'GCP Spanner': { source: 'cloud', slug: 'gcp/cloud_spanner/cloud_spanner.svg' },
  'GCP Secret Manager': { source: 'cloud', slug: 'gcp/secret_manager/secret_manager.svg' },
};

const DEVICON_BASE = 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons';

function buildIconUrl(entry: IconEntry): string {
  switch (entry.source) {
    case 'devicon':
      const variant = entry.variant ?? 'original';
      return `${DEVICON_BASE}/${entry.slug}/${entry.slug}-${variant}.svg`;
    case 'simpleicons':
      return `https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/${entry.slug}.svg`;
    case 'svgl':
      return `https://svgl.app/library/${entry.slug}.svg`;
    case 'selfhst':
      return `https://cdn.jsdelivr.net/gh/selfhst/icons/svg/${entry.slug}.svg`;
    case 'cloud':
      return `https://cdn.jsdelivr.net/gh/tf2d2/icons@main/${entry.slug}`;
    case 'local':
      return entry.slug; // static public path
  }
}

function normalize(label: string): string {
  return label.toLowerCase().replace(/[\s.\-_]/g, '');
}

const LOOKUP = new Map<string, IconEntry>();
for (const [key, entry] of Object.entries(ICON_REGISTRY)) {
  LOOKUP.set(normalize(key), entry);
}

export function getIconUrl(label: string): string | null {
  const entry = LOOKUP.get(normalize(label));
  return entry ? buildIconUrl(entry) : null;
}
